export const dataEventovFooter = [
    {
        name: "Cadfgrthehwrthey",
        members: "4",
        address: "007 DuBuque Spur",
        location: "https://goo.gl/maps/eQQamVapvuiYijht8",
        description:
            "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
        author: "Rose Purdy",
        photo: "https://loremflickr.com/640/480/nature",
        status: "status 1",
        date: "2023-10-10",
        start: "12:00",
        end: "16:00",
        id: "1",
    },
    {
        name: "CSSSSSSSSSSS",
        members: "4",
        address: "007 DuBuque Spur",
        location: "https://goo.gl/maps/eQQamVapvuiYijht8",
        description:
            "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
        author: "Rose Purdy",
        photo: "https://loremflickr.com/640/480/nature",
        status: "status 1",
        date: "2023-11-18",
        start: "12:00",
        end: "16:00",
        id: "2",
    },
    {
        name: "SSSSSSSSSSSD",
        members: "4",
        address: "007 DuBuque Spur",
        location: "https://goo.gl/maps/eQQamVapvuiYijht8",
        description:
            "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
        author: "Rose Purdy",
        photo: "https://loremflickr.com/640/480/nature",
        status: "status 1",
        date: "2023-12-03",
        start: "12:00",
        end: "16:00",
        id: "3",
    },
    {
        name: "SDFFFFFFFFFFFF",
        members: "4",
        address: "007 DuBuque Spur",
        location: "https://goo.gl/maps/eQQamVapvuiYijht8",
        description:
            "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
        author: "Rose Purdy",
        photo: "https://loremflickr.com/640/480/nature",
        status: "status 1",
        date: "2023-05-10",
        start: "12:00",
        end: "16:00",
        id: "4",
    },
    {
        name: "Carlie",
        members: "4",
        address: "007 DuBuque Spur",
        location: "https://goo.gl/maps/eQQamVapvuiYijht8",
        description:
            "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
        author: "Rose Purdy",
        photo: "https://loremflickr.com/640/480/nature",
        status: "status 1",
        date: "2023-05-10",
        start: "12:00",
        end: "16:00",
        id: "5",
    },
]